[helpers]

[default]
depends = ["fish", "tmux", "bat", "lvim"]

[default.files]

[default.variables]

[zed.files]
"zed/themes" = "~/.config/zed/themes"
"zed/settings.json" = "~/.config/zed/settings.json"
"zed/keymap.json" = "~/.config/zed/keymap.json"

[fish.files]
"fish/fish_plugins" = "~/.config/fish/fish_plugins"
"fish/functions/" = "~/.config/fish/functions/"

[lvim.files]
"lvim/config.lua" = "~/.config/lvim/config.lua"

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[bat.files]
bat = "~/.config/bat/config"

